### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by ayushnanda21** [BITSoC/iBlog#13]
Navbar seems to be less attractive and eye catchy and nothings shows up on clicking about and contact me too. So I want to make some enchancements and linking the empty tabs to some data.

**Comment by parasg1999** [comment]
I would suggest working on the core functionality first rather than worrying about the navbar. The writing experience needs to be made better for the project to be actually good.
However if you want to work on the Navbar, you can do so. Just be sure to test the code before making a PR.
