### ISSUE TITLE
Adding GitHub actions to iBlog

### ISSUE THREAD

**Issue by iamrajiv** [BITSoC/iBlog#2]

**Comment by iamrajiv** [comment]
@parasg1999 I want to work on this issue.

**Comment by parasg1999** [comment]
What github actions do you suggest? I would prefer an eslint config file for formatting.

**Comment by iamrajiv** [comment]
@parasg1999 Yeah, I want to suggest the same i.e. ESLint. Also, I would suggest adding Prettier too.

**Comment by parasg1999** [comment]
Yeah, please go ahead :tada:

**Comment by iamrajiv** [comment]
@parasg1999 Can you labelled this issue?

**Comment by parasg1999** [comment]
Is this fine?

**Comment by iamrajiv** [comment]
@parasg1999 You can also make some labels and tags like bitsoc, documentation, bug, enhancement etc which will enhance the workflow.

**Comment by parasg1999** [comment]
Github actions are great but I'd still like someone to add pretest scripts on the client side

**Comment by parasg1999** [comment]
The prettier is still not working, would like you to review it - @iamrajiv
