### ISSUE TITLE
Adding of pull request and issue template

### ISSUE THREAD

**Issue by iamrajiv** [BITSoC/iBlog#6]

**Comment by iamrajiv** [comment]
@parasg1999 I want to work on this issue

**Comment by parasg1999** [comment]
Issues won't always contain bugs, but you add the PR template

**Comment by iamrajiv** [comment]
@parasg1999 I will try to use the new form of ISSUE_TEMPLATE i.e. making a folder `ISSUE_TEMPLATE` in `.github` and adding different `.md` files for different issues like`bug.md`, `documentation.md`, `proposal.md`, `feature.md` etc. A contributor can choose the type of issue whenever they make an issue.

**Comment by parasg1999** [comment]
Great!

**Comment by parasg1999** [comment]
Could you make the PR, I can't open that since the repository was deleted

**Comment by parasg1999** [comment]
Added in #15
